import type { Metadata } from "next";
import { Inter} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes"
import NavBar from "./components/NavBar";
import SideBar from "./components/SideBar";


const inter = Inter({
  subsets: ["latin"]
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html suppressHydrationWarning
      lang="en"
      className={`${inter.className} h-full `}
    >
      <body className="min-h-screen flex flex-col">
        <ThemeProvider attribute="class" enableSystem defaultTheme="light">
          <div className="grid min-h-screen grid-cols-1 grid-rows-[auto_1fr] md:grid-cols-[250px_1fr] md:grid-rows-[auto_1fr]">
            <aside className="hidden md:block md:row-span-2 w-full h-full ">
              <SideBar />
            </aside>
            <header className="col-span-1 md:col-start-2 w-full  ">
              <NavBar/>
            </header>
            <main className="w-full h-full md:col-start-2 md:row-start-2 bg-slate-100">
              {children}
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
